-- ---------------------------------------------------------------------------
-- Foundations: enums, ID sequences, and shared helpers.
--
-- Every enum below mirrors a closed union in frontend/src/types/. Where the
-- contract leaves a union open with `(string & {})` — medicine category and
-- unit — the column stays `text`, because the design's own dropdowns allow
-- free entry there.
--
-- Two representation choices worth stating once, since every later migration
-- depends on them:
--
--   * Clock times are `text` matching 'HH:MM', not Postgres `time`. The
--     contract's TimeString is 'HH:mm' and `time` renders as '08:00:00', so
--     storing `time` would mean formatting on every read and one missed spot
--     showing "08:00:00" in the UI. Zero-padded 24-hour text sorts correctly
--     and compares correctly, which is all slots need.
--   * Dates are `date` and timestamps are `timestamptz`. PostgREST already
--     serialises those as 'YYYY-MM-DD' and ISO 8601, matching DateString and
--     DateTimeString exactly.
-- ---------------------------------------------------------------------------

create type weekday as enum (
  'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'
);

-- Operating Hours adds a 'holidays' row alongside the weekdays.
create type operating_hours_key as enum (
  'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday',
  'holidays'
);

-- The five statuses in the Booking Requests table and the dashboard pie chart.
-- `no_show` is deliberately absent: it appears nowhere in the prototype, and a
-- sixth value would add a wedge to a chart designed around five.
create type appointment_status as enum (
  'pending', 'confirmed', 'rescheduled', 'cancelled', 'completed'
);

create type staff_role as enum ('administrator', 'staff');
create type staff_status as enum ('active', 'inactive');

create type sex as enum ('male', 'female');
create type civil_status as enum ('single', 'married', 'widowed', 'separated');
create type blood_type as enum ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-');
create type visit_type as enum ('prenatal', 'delivery', 'postnatal');

create type patient_document_type as enum (
  'valid_id',
  'lab_results',
  'ultrasound_report',
  'marriage_certificate',
  'previous_hospital_records'
);

create type dosage_form as enum (
  'Tablet', 'Capsule', 'Syrup', 'Injection', 'Ointment'
);

create type stock_movement_type as enum ('stock_in', 'stock_out');
create type stock_status as enum ('good', 'low', 'out');

create type reschedule_request_status as enum ('pending', 'approved', 'declined');

-- ---------------------------------------------------------------------------
-- Human-facing identifiers
--
-- BR-0812, P-108, EMP-0001. Generated by the database rather than application
-- code so two concurrent inserts cannot mint the same one. `nextval` is legal
-- in a DEFAULT expression, which is what makes this work without a trigger.
-- ---------------------------------------------------------------------------

create sequence booking_ref_seq start 812;
create sequence patient_code_seq start 108;
create sequence employee_id_seq start 1;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- Maps a date to a weekday.
--
-- Deliberately built on ISODOW rather than `to_char(d, 'Day')`: to_char's day
-- names come from the server's lc_time, so a locale change would silently
-- start returning names that fail the enum cast. ISODOW is 1=Monday..7=Sunday
-- everywhere, always.
create function weekday_of(d date) returns weekday
language sql
immutable
strict
as $$
  select (array[
    'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'
  ]::weekday[])[extract(isodow from d)::int];
$$;

-- ---------------------------------------------------------------------------
-- "Today", as the clinic means it.
--
-- The database runs in UTC and the clinic is in Caloocan City, UTC+8. For the
-- eight hours between Manila midnight and UTC midnight, `current_date` is
-- *yesterday* as far as the database is concerned — so Today's Schedule would
-- show the wrong day every evening, a booking for this morning would be
-- rejected as being in the past, and Days Left would be off by one.
--
-- Every business rule that needs a date uses this, not `current_date`.
-- ---------------------------------------------------------------------------
create function clinic_today() returns date
language sql
stable
as $$
  select (now() at time zone 'Asia/Manila')::date;
$$;

create function set_updated_at() returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Clock time as the contract spells it: zero-padded 24-hour 'HH:MM'.
create domain clock_time as text
  check (value ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$');
